version: '2.1'
networks:
  elastic:
volumes:
  filebeatdata:
  filebeatlog:

services:
  elasticsearch:
    image: elastic_es:1.0.0
    build:
      context: ./elasticsearch
      args:
        - elk_version=$ES_VERSION
    container_name: elasticsearch
    restart: on-failure
    environment:
      - node.name=$HOST
      - network.publish_host=$HOST
      - discovery.seed_hosts=10.100.172.116:9301,10.100.172.117:9301,10.100.216.143:9301
      - cluster.initial_master_nodes=10.100.172.116,10.100.172.117,10.100.216.143
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
      - /usr/share/elasticsearch/logs:/usr/share/elasticsearch/logs
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
    ports: ['9201:9201', '9301:9301']
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ['CMD', 'curl', '-s', '-f', 'http://localhost:9201/_cat/health']
    # command:
    #   - /bin/bash
    #   - -c
    #   - |
    #     bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v${ES_VERSION}/elasticsearch-analysis-ik-${ES_VERSION}.zip
    #     bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-pinyin/releases/download/v${ES_VERSION}/elasticsearch-analysis-pinyin-${ES_VERSION}.zip

  kibana:
    image: elastic/kibana:$ES_VERSION
    container_name: kibana
    restart: on-failure
    volumes: ['./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml']
    networks: ['elastic']
    ports: ['5602:5602']
    healthcheck:
      test: ['CMD', 'curl', '-s', '-f', 'http://localhost:5602/']
    depends_on:
      elasticsearch: { condition: service_healthy }
    environment:
      - SERVER_NAME=$HOST
      - ELASTICSEARCH_HOSTS=["http://10.100.172.116:9201","http://10.100.172.117:9201","http://10.100.216.143:9201"]

  filebeat:
    image: elastic/filebeat:$ES_VERSION
    container_name: filebeat
    restart: on-failure
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/modules.d/elasticsearch.yml:/usr/share/filebeat/modules.d/elasticsearch.yml
      - ./filebeat/prospectors.d/:/usr/share/filebeat/prospectors.d
      - filebeatdata:/usr/share/filebeat/data/
      - filebeatlog:/usr/share/filebeat/logs/
      - /usr/share/elasticsearch/logs/:/var/log/elasticsearch/:ro
      - /var/log/:/var/log/host:ro
      - /var/lib/docker/containers:/hostfs/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks: ['elastic']
    command: filebeat -e -strict.perms=false
    depends_on:
      elasticsearch: { condition: service_healthy }
    environment:
      - KIBANA_HOST="http://$HOST:5602"
      - ELASTICSEARCH_HOSTS=["http://10.100.172.116:9201","http://10.100.172.117:9201","http://10.100.216.143:9201"]
