ARG elk_version
FROM elastic/elasticsearch:$elk_version
ARG elk_version
# RUN bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v${elk_version}/elasticsearch-analysis-ik-${elk_version}.zip \
#   && bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-pinyin/releases/download/v${elk_version}/elasticsearch-analysis-pinyin-${elk_version}.zip
